#!/bin/bash
set -e

node_modules/component/bin/component build --standalone Indexed --out tmp --name standalone-build
sed -i.bak 's/require/requireIndexed/' tmp/standalone-build.js
cp ./tmp/standalone-build.js ./indexed.js
